# 生产环境配置
spring:
  application:
    name: comp9900-management-module01

  # 允许Bean覆盖
  main:
    allow-bean-definition-overriding: true

  # 配置数据库连接信息
  datasource:
    url: jdbc:postgresql://db:5432/my_app_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin123
    # 添加数据库初始化配置
    initialization-mode: always
    schema: classpath:db/init_schema.sql
    continue-on-error: true
  
  # SQL脚本初始化配置  
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init_schema.sql
      continue-on-error: true
  
  # 禁用AOP自动代理
  aop:
    auto: false
    proxy-target-class: false
  
  jwt:
    secret: VGhpczI1NkJpdFNlY3JldEtleUZvckpXVDEyMzQ1NkBA
    expiration: 86400000

# 配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 配置连接池
datasource:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1

# 日志配置
logging:
  level:
    root: INFO
    com.unsw: INFO
    org.springframework: WARN 